name: dto_builder
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.1

# Add regular dependencies here.
dependencies:
  interact_cli: ^2.4.0
  barbecue: ^0.5.0
  args: ^2.6.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
